# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  hybridrag:
    build:
      args:
        IMAGE_REPO: ${REGISTRY}
        BASE_TAG: ${TAG}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: ./Dockerfile
    image: ${REGISTRY:-opea}/hybridrag:${TAG:-latest}

  struct2graph: 
    build: 
      context: GenAIComps
      dockerfile: comps/struct2graph/src/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/struct2graph:${TAG:-latest}

  text2cypher: 
    build: 
      context: GenAIComps
      dockerfile: comps/text2cypher/src/Dockerfile.intel_hpu
    extends: hybridrag
    image: ${REGISTRY:-opea}/text2cypher:${TAG:-latest}

  embedding:
    build:
      context: GenAIComps
      dockerfile: comps/embeddings/src/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/embedding:${TAG:-latest}
  vllm:
    build:
      context: vllm
      dockerfile: Dockerfile.cpu
    extends: hybridrag
    image: ${REGISTRY:-opea}/vllm:${TAG:-latest}
  dataprep:
    build:
      context: GenAIComps
      dockerfile: comps/dataprep/src/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}

  hybridrag-ui:
    build:
      context: ../ui
      dockerfile: ./docker/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/hybridrag-ui:${TAG:-latest}
  hybridrag-conversation-ui:
    build:
      context: ../ui
      dockerfile: ./docker/Dockerfile.react
    extends: hybridrag
    image: ${REGISTRY:-opea}/hybridrag-conversation-ui:${TAG:-latest}
  retriever:
    build:
      context: GenAIComps
      dockerfile: comps/retrievers/src/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/retriever:${TAG:-latest}
  reranking:
    build:
      context: GenAIComps
      dockerfile: comps/rerankings/src/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/reranking:${TAG:-latest}
  llm-textgen:
    build:
      context: GenAIComps
      dockerfile: comps/llms/src/text-generation/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
  guardrails:
    build:
      context: GenAIComps
      dockerfile: comps/guardrails/src/guardrails/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/guardrails:${TAG:-latest}
#    ##########################################################
#  vllm-gaudi:
#    build:
#      context: vllm-fork
#      dockerfile: Dockerfile.hpu
#    extends: hybridrag
#    image: ${REGISTRY:-opea}/vllm-gaudi:${TAG:-latest}
#    ##########################################################
  nginx:
    build:
      context: GenAIComps
      dockerfile: comps/third_parties/nginx/src/Dockerfile
    extends: hybridrag
    image: ${REGISTRY:-opea}/nginx:${TAG:-latest}
